### ISSUE TITLE
URL https://onesignal.com/api/v1/notifications IS NOT AVAILABLE

### ISSUE THREAD

**Issue by matiasAS** [OneSignal/api#11]
Hi, I'm trying to send notifications with the API, but when I make a request to https://onesignal.com/api/v1/notifications, I get a 404 error. I would appreciate solving it as soon as possible.

![image](https://user-images.githubusercontent.com/7276332/168327661-4d61ad9e-6b69-4e29-a7ec-87c25fa304fe.png)

Regards
Matias

**Comment by nan-li** [comment]
Hi @matiasAS,

Your screen shows `v2` in the browser URL. That may be the issue, try again with the correct URL.

**Comment by matiasAS** [comment]
hello @nan-li 
sorry, it was my mistake in the image, but effectively when I tried with v1 it told me that the url was not found, but now it is available, thanks!
