### ISSUE TITLE
Create app API

### ISSUE THREAD

**Issue by Kalo2412** [OneSignal/api#40]
Hi, I am trying to automate the process of creating new app in my one signal organization. Currently I am calling this endpoint 
https://documentation.onesignal.com/reference/create-an-app -> to create and app -> but in the response I get "basic_auth_key":null, I presume this should be the REST API Key for the application created in order to send notifications. However I need this key in my code for further set up processing, How can I force it to not be null or how can I get it?

**Comment by nan-li** [comment]
Hi @Kalo2412, in order to create a new application, you need an elevated permission. 
You need to use the **User Auth Key** instead of the **REST API Key**.

This is noted in the API documentation, see the link for how to get your User Auth Key.

> Requires your OneSignal User Auth Key, available in [Account & API Keys](https://documentation.onesignal.com/docs/accounts-and-keys#user-auth-key).

**Comment by Kalo2412** [comment]
Here is a snippet, the app is created successfully but in the response the REST API Key for the newly created app is null

---------------
def onesignal():
    url = "https://api.onesignal.com/apps"
    payload = {
        "name": "Test New App",
        "organization_id": "***",
        "apns_key_id": "***",
        "apns_team_id": "***",
        "apns_bundle_id": "or*********pp",
        "apns_p8": "***"
    }
    headers = {
        "accept": "text/plain",
        "Content-Type": "application/json",
        "Authorization": "Basic **here I am using the User Auth Key**"
    }
    response = requests.post(url, json=payload, headers=headers)
    data = response.json()
    key = data.get('basic_auth_key')
    print(key)
--------------  

The id is null. As per the doc the sample response is as following:

--------
{
  id: "e4e87830-b954-11e3-811d-f3b376925f15",
  name: "Your app 1",
  players: 0,
  messageable_players: 0,
  updated_at: "2014-04-01T04:20:02.003Z",
  created_at: "2014-04-01T04:20:02.003Z",
  organization_id: "551731e5-dbd5-4471-a222-2e6ae31aee31",
  gcm_key: "a gcm push key",
  chrome_web_origin: "Chrome Web Push Site URL",
  chrome_web_default_notification_icon: "http://yoursite.com/chrome_notification_icon",
  chrome_web_sub_domain:"your_site_name",
  apns_env: "production",
  apns_certificates: "Your apns certificate",
  safari_apns_certificate: "Your Safari APNS certificate",
  safari_site_origin: "The homename for your website for Safari Push, including http or https",
  safari_push_id: "The certificate bundle ID for Safari Web Push",
  safari_icon_16_16: "http://onesignal.com/safari_packages/e4e87830-b954-11e3-811d-f3b376925f15/16x16.png",
  safari_icon_32_32: "http://onesignal.com/safari_packages/e4e87830-b954-11e3-811d-f3b376925f15/16x16@2.png",
  safari_icon_64_64: "http://onesignal.com/safari_packages/e4e87830-b954-11e3-811d-f3b376925f15/32x32@2x.png",
  safari_icon_128_128: "http://onesignal.com/safari_packages/e4e87830-b954-11e3-811d-f3b376925f15/128x128.png",
  safari_icon_256_256: "http://onesignal.com/safari_packages/e4e87830-b954-11e3-811d-f3b376925f15/128x128@2x.png",
  site_name: "The URL to your website for Web Push",  
  basic_auth_key: "NGEwMGZmMjItY2NkNy0xMWUzLTk5ZDUtMDAwYzI5NDBlNjJj"
}

---------
Here the basic auth key is not null

**Comment by Hantex9** [comment]
Hi @Kalo2412, I also encountered the same issue with my app automation process on OneSignal. After contacting OneSignal support, I discovered they removed the "basic_auth_key" field from the response for security reasons. To see this key in the response, the admin email associated with the user auth token calling the "createApp" API needs to be whitelisted. In my case, OneSignal support added my email to the whitelist through the support ticket I opened. After that, the "basic_auth_key" field was populated in the response.

**Comment by nan-li** [comment]
Hi @Kalo2412, apologies, I misunderstood the question, thank you @Hantex9  for your followup. 

Yes, if you do not see the necessary keys, please reach out to our support team at support@onesignal.com to enable elevated permission for your account.

**Comment by Kalo2412** [comment]
Thank you very much, all! I will contact the support! Nice day!
